### Get data from the db:

GET http://localhost:3000/arduino


### POST data to the arduino

POST http://localhost:3000/write
Content-Type: application/json

{
  "id": 15,
  "timestamp": "9:24",
  "sensorId": "12",
  "status": "nomotion"
}